services:
  sub-mirror:
    build:
      context: .
      dockerfile: Dockerfile
    image: sub-mirror:local
    ports:
      - "0.0.0.0:25500:8788"
    volumes:
      - ./data:/data
      - ./resources/profiles:/profiles:ro
    environment:
      SUB_URL: ""
      OUTPUT: "clash"
      USE_CONVERTER: "1"
      AUTH_SESSION_TTL_SEC: "2592000"
      CONVERTER_URL: "http://127.0.0.1:8787/sub"
      SOURCE_URL: "http://127.0.0.1:8788/source.txt"
      ADMIN_SEED_PATH: "/resources/admin.json"
      PROFILE_DIR: "/profiles"
      APP_PORT: "8788"
      SUBCONVERTER_PORT: "8787"
